{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jellyfin.fullname" . }}
  namespace: {{ include "jellyfin.name" . }}
  labels:
    app: {{ include "jellyfin.name" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: {{ $.Values.service.jellyfin.port }}
    - host: {{ $.Values.service.jackett.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: {{ $.Values.service.jackett.port }}
    - host: {{ $.Values.service.sonarr.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: {{ $.Values.service.sonarr.port }}
    - host: {{ $.Values.service.radarr.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: {{ $.Values.service.radarr.port }}
    - host: {{ $.Values.service.qbittorrent.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: {{ $.Values.service.qbittorrent.port }}
    - host: {{ $.Values.service.readingglasses.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: {{ $.Values.service.readingglasses.port }}
    - host: {{ $.Values.service.bookshelf.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" $ }}
                port:
                  number: {{ $.Values.service.bookshelf.port }}
{{- end }}
