apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jellyfin.fullname" . }}
  namespace: {{ include "jellyfin.name" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "jellyfin.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "jellyfin.name" . }}
    spec:
      volumes:
        - name: {{ include "jellyfin.name" . }}-config-data
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.name" . }}-config-pvc
            readOnly: false
        - name: {{ include "jellyfin.name" . }}-cache-data
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.name" . }}-cache-pvc
            readOnly: false
        - name: {{ include "jellyfin.name" . }}-media-data
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.name" . }}-media-pvc
            readOnly: false
        - name: {{ .Values.service.jackett.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.jackett.name }}-pvc
            readOnly: false
        - name: {{ .Values.service.sonarr.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.sonarr.name }}-pvc
            readOnly: false
        - name: {{ .Values.service.radarr.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.radarr.name }}-pvc
            readOnly: false
        - name: {{ .Values.service.qbittorrent.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.qbittorrent.name }}-pvc
            readOnly: false
        - name: {{ .Values.service.qbittorrent.name }}-downloads-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.qbittorrent.name }}-downloads-pvc
            readOnly: false
        - name: {{ .Values.service.bookshelf.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.bookshelf.name }}-pvc
            readOnly: false
        - name: {{ .Values.service.rrgglasses.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.rrgglasses.name }}-pvc
            readOnly: false
        - name: {{ .Values.service.rrgglasses.name }}-db-data
          persistentVolumeClaim:
            claimName: {{ .Values.service.rrgglasses.name }}-db-pvc
            readOnly: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.jellyfin.repository }}:{{ .Values.image.jellyfin.tag }}"
          imagePullPolicy: {{ .Values.image.jellyfin.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.jellyfin.port }}
            - name: udp-port
              containerPort: {{ .Values.service.jellyfin.udpPort }}
              protocol: UDP
          volumeMounts:
            - name: {{ include "jellyfin.name" . }}-config-data
              mountPath: {{ .Values.volumes.jellyfin.mountPath.config }}
            - name: {{ include "jellyfin.name" . }}-cache-data
              mountPath: {{ .Values.volumes.jellyfin.mountPath.cache }}
            - name: {{ include "jellyfin.name" . }}-media-data
              mountPath: {{ .Values.volumes.jellyfin.mountPath.media }}
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: {{ .Values.ingress.host }}
            - name: TZ
              value: {{ .Values.envVars.common.TZ }}

        - name: {{ .Values.service.jackett.name }}
          image: "{{ .Values.image.jackett.repository }}:{{ .Values.image.jackett.tag }}"
          imagePullPolicy: {{ .Values.image.jackett.pullPolicy }}
          ports:
            - name: {{ .Values.service.jackett.name }}
              containerPort: {{ .Values.service.jackett.port }}
          volumeMounts:
            - name: {{ .Values.service.jackett.name }}-data
              mountPath: {{ .Values.volumes.jackett.mountPath.config }}
          env:
            - name: TZ
              value: {{ .Values.envVars.common.TZ }}

        - name: {{ .Values.service.sonarr.name }}
          image: "{{ .Values.image.sonarr.repository }}:{{ .Values.image.sonarr.tag }}"
          imagePullPolicy: {{ .Values.image.sonarr.pullPolicy }}
          ports:
            - name: {{ .Values.service.sonarr.name }}
              containerPort: {{ .Values.service.sonarr.port }}
          volumeMounts:
            - name: {{ .Values.service.sonarr.name }}-data
              mountPath: {{ .Values.volumes.sonarr.mountPath.config }}
            - name: {{ include "jellyfin.name" . }}-media-data
              #Sonarr needs to download files to the same directory the jellyfin uses to expose them
              mountPath: {{ .Values.volumes.jellyfin.mountPath.media }}
            - name: {{ .Values.service.qbittorrent.name }}-downloads-data
              mountPath: {{ .Values.volumes.qbittorrent.mountPath.downloads }}
          env:
            - name: TZ
              value: {{ .Values.envVars.common.TZ }}

        - name: {{ .Values.service.radarr.name }}
          image: "{{ .Values.image.radarr.repository }}:{{ .Values.image.radarr.tag }}"
          imagePullPolicy: {{ .Values.image.radarr.pullPolicy }}
          ports:
            - name: {{ .Values.service.radarr.name }}
              containerPort: {{ .Values.service.radarr.port }}
          volumeMounts:
            - name: {{ .Values.service.radarr.name }}-data
              mountPath: {{ .Values.volumes.radarr.mountPath.config }} 
            - name: {{ include "jellyfin.name" . }}-media-data
              #Radarr needs to download files to the same directory the jellyfin uses to expose them
              mountPath: {{ .Values.volumes.jellyfin.mountPath.media }}
            - name: {{ .Values.service.qbittorrent.name }}-downloads-data
              mountPath: {{ .Values.volumes.qbittorrent.mountPath.downloads }}
          env:
            - name: TZ
              value: {{ .Values.envVars.common.TZ }}

        - name: {{ .Values.service.qbittorrent.name }}
          image: "{{ .Values.image.qbittorrent.repository }}:{{ .Values.image.qbittorrent.tag }}"
          imagePullPolicy: {{ .Values.image.qbittorrent.pullPolicy }}
          ports:
            - name: {{ .Values.service.qbittorrent.name }}
              containerPort: {{ .Values.service.qbittorrent.port }}
            - name: qb-udp-port
              containerPort: {{ .Values.service.qbittorrent.udpPort }}
              protocol: UDP
          volumeMounts:
            - name: {{ .Values.service.qbittorrent.name }}-data
              mountPath: {{ .Values.volumes.qbittorrent.mountPath.config }}
            - name: {{ .Values.service.qbittorrent.name }}-downloads-data
              mountPath: {{ .Values.volumes.qbittorrent.mountPath.downloads }}
          env:
            - name: TZ
              value: {{ .Values.envVars.common.TZ }}
            - name: PGID
              value: {{ .Values.envVars.qbittorrent.PGID | quote }}
            - name: PUID
              value: {{ .Values.envVars.qbittorrent.PUID | quote }}
            - name: WEBUI_PORT
              value: {{ .Values.service.qbittorrent.port | quote }}
            - name: TORRENTING_PORT
              value: {{ .Values.service.qbittorrent.udpPort | quote }}

        - name: {{ .Values.service.bookshelf.name }}
          image: "{{ .Values.image.bookshelf.repository }}:{{ .Values.image.bookshelf.tag }}"
          imagePullPolicy: {{ .Values.image.bookshelf.pullPolicy }}
          ports:
            - name: {{ .Values.service.bookshelf.name }}
              containerPort: {{ .Values.service.bookshelf.port }}
          volumeMounts:
            - name: {{ .Values.service.bookshelf.name }}-data
              mountPath: {{ .Values.volumes.bookshelf.mountPath.config }}
            - name: {{ .Values.service.qbittorrent.name }}-downloads-data
              mountPath: {{ .Values.volumes.qbittorrent.mountPath.downloads }}

        - name: {{ .Values.service.rrgglasses.name }}
          image: "{{ .Values.image.rrgglasses.repository }}:{{ .Values.image.rrgglasses.tag }}"
          imagePullPolicy: {{ .Values.image.rrgglasses.pullPolicy }}
          command: {{ .Values.commands.rrgglasses.entrypoint }}
          ports:
            - name: {{ .Values.service.rrgglasses.name }}
              containerPort: {{ .Values.service.rrgglasses.port }}
          volumeMounts:
            - name: {{ .Values.service.rrgglasses.name }}-data
              mountPath: {{ .Values.volumes.rrgglasses.mountPath.config }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rrg-glasses-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: {{ .Values.envVars.rrgglasses.POSTGRES_HOST }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.envVars.rrgglasses.POSTGRES_DATABASE }}
            - name: POSTGRES_USER
              value: {{ .Values.envVars.rrgglasses.POSTGRES_USER }}

        - name: {{ .Values.service.rrgglassesdb.name }}
          image: "{{ .Values.image.rrgglassesdb.repository }}:{{ .Values.image.rrgglassesdb.tag }}"
          imagePullPolicy: {{ .Values.image.rrgglassesdb.pullPolicy }}
          ports:
            - name: {{ .Values.service.rrgglassesdb.name }}
              containerPort: {{ .Values.service.rrgglassesdb.port }}
          volumeMounts:
            - name: {{ .Values.service.rrgglasses.name }}-db-data
              mountPath: {{ .Values.volumes.rrgglassesdb.mountPath.dbData }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rrg-glasses-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: {{ .Values.envVars.rrgglassesdb.POSTGRES_USER }}
            - name: POSTGRES_DB
              value: {{ .Values.envVars.rrgglassesdb.POSTGRES_DB }}
