apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}
  namespace: {{ include "homeassistant.name" . }}
  labels:
    app: {{ include "homeassistant.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "homeassistant.name" . }}
